apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-test-service
  labels:
    app: ws-test-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ws-test-service
  template:
    metadata:
      labels:
        app: ws-test-service
    spec:
      containers:
      - name: ws-test-service
        image: ws-test-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20