apiVersion: v1
kind: Service
metadata:
  name: ws-server
  labels:
    app: ws-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ws-server